### ISSUE TITLE
How to inference?

### ISSUE THREAD

**Issue by tigermask1978** [Peeples-Lab/HLTDNN#2]
Since the traing data is the segments of the original .wav file, then how to inference on the whole .wav file?

Thanks a lot.

**Comment by jarinritu** [comment]
@tigermask1978 Since the DeepShip dataset was segmented into 3 second chunks for training, validation, and testing, the model can be directly applied to the validation and test segments for inference. No special processing is required; the segmented data structure matches the training set. For new full audio files, a sliding window approach could provide inter-segment context, but for this dataset, the model can be run on the validation and test chunks as-is.
Let me know if this helps explain how to perform inference or if you need any clarification! Thanks!

**Comment by tigermask1978** [comment]
I want to know giving a new full audio file, how to inference its class type. I am not quite understanding what you say "a sliding window approach could provide inter-segment context".Could you give me some sample code?

Thanks.

**Comment by jarinritu** [comment]
@tigermask1978 For a new full audio file, there are several ways to combine predictions. The most straightforward would be a majority vote, as illustrated in the figure below.
[
[Majority Vote.pdf](https://github.com/Advanced-Vision-and-Learning-Lab/HLTDNN/files/13338380/Majority.Vote.pdf)
](url)

**Comment by jarinritu** [comment]
@tigermask1978 To use our models, an audio signal will need to be divided into three second segments (i.e., apply sliding window to do this). Once the segments are created, the segments will need to be passed through the models. Each segment will then have its own class prediction. Here is an example: say we had a new full audio signal that was from Cargo and 60 seconds in total length. If we use a three second window (no overlap, hop length of three seconds) on the signal, this will result in 20 segments. Ideally, the model should classify all segments as Cargo. However, the model may incorrectly classify one or more segment(s). To classify the entire signal, you will need to combine predictions. The most straightforward would be a majority vote, as illustrated in the figure below
![majority_vote](https://github.com/Advanced-Vision-and-Learning-Lab/HLTDNN/assets/33591317/e6ee5f55-9635-4f53-afdd-da188ca25846).
