### ISSUE TITLE
Can not achieve the training accuracy listed on paper

### ISSUE THREAD

**Issue by Larry-Ye** [Peeples-Lab/HLTDNN#4]
I use the identical training parameters listed on paper. After serveral times of trying, the evaluation accuracy is lower than the accuracy listed on paper. The average confusion matrix is at here.

![image](https://github.com/Advanced-Vision-and-Learning-Lab/HLTDNN/assets/71308801/748774aa-bd5c-466c-a5d9-4865c227a46f)

The overall accuracy is 53.06 ± 1.23, which is lower than the paper decleared 59.21 ± 0.56.

Could you release the your trained weight? Thank you.

**Comment by jarinritu** [comment]
Hello @Larry-Ye,
Thanks for reaching out. To verify, are you referring to training or testing accuracy? The 59.21 ± 1.23 is the testing accuracy.
There are various factors that could contribute to differences in accuracy, including:
**1. Experimental Environment:** Our experiments were conducted on an NVIDIA RTX 3090 using Linux. Using different operating systems like macOS or Windows could lead to variations in accuracy.
**2. Dataset Completeness:** Please make sure you have downloaded the complete dataset as shown [here](https://github.com/Advanced-Vision-and-Learning-Lab/HLTDNN/tree/master/Datasets#deepship). Using only a portion of the dataset instead of all the files could impact performance. Verify that the number of signals and segments matches the diagram.
**3. Updates in processing and normalization Techniques:** We recently updated our data processing and normalization techniques, which could potentially affect the model's accuracy. We will make sure to update the repository to reflect the latest version described in the paper.
If your setup aligns with these aspects, I recommend downloading the updated repository and rerunning the experiments. Additionally, here's the link to the model's weights: [Link](https://drive.google.com/drive/folders/1-5Bd0u8XeuxN9x7Z3XObQ-5ibls9ayRY?usp=sharing)
Please let me know if you need further assistance.

**Comment by Larry-Ye** [comment]
> Hello @Larry-Ye, Thanks for reaching out. To verify, are you referring to training or testing accuracy? The 59.21 ± 1.23 is the testing accuracy. There are various factors that could contribute to differences in accuracy, including: **1. Experimental Environment:** Our experiments were conducted on an NVIDIA RTX 3090 using Linux. Using different operating systems like macOS or Windows could lead to variations in accuracy. **2. Dataset Completeness:** Please make sure you have downloaded the complete dataset as shown [here](https://github.com/Advanced-Vision-and-Learning-Lab/HLTDNN/tree/master/Datasets#deepship). Using only a portion of the dataset instead of all the files could impact performance. Verify that the number of signals and segments matches the diagram. **3. Updates in processing and normalization Techniques:** We recently updated our data processing and normalization techniques, which could potentially affect the model's accuracy. We will make sure to update the repository to reflect the latest version described in the paper. If your setup aligns with these aspects, I recommend downloading the updated repository and rerunning the experiments. Additionally, here's the link to the model's weights: [Link](https://drive.google.com/drive/folders/1-5Bd0u8XeuxN9x7Z3XObQ-5ibls9ayRY?usp=sharing) Please let me know if you need further assistance.

Thank you I will have a try.
